from marshmallow import fields
from app.ext import marsMallow

class RatingSchema(marsMallow.Schema):
    gridVoltatge = String()
    gridCurrent = String()
    acOutputVoltage = String()
    acOutputFrequency = String()
    acOutputCurrent = String()
    acOutputApparentCurrent = String()
    acOutputActivePower = String()
    batteryVoltage = String()
    batteryRechargeVoltage = String()
    batteryUnderVoltage = String()
    batteryBulkVoltage = String()
    batteryFloatVoltage = String()
    batteryType = String()
    currentMaxAcChargingCurrent = String()
    currentMaxChargingCurrent = String()
    inputVoltageRange = String()
    outputSourcePriority == String()
    chargerSourcePriority == String()
    parallelMaxNum == String()
    machineType == String()
    topology = String()
    outputMode = String()
    batteryRedischargeVoltage = String()
    pvOkConditionForParallel = String()
    pvPowerBalance = String()

class StatusSchema(marsMallow.Schema):
    gridVoltatge = String()
    gridFrequency = String()
    acOutputVoltage = String()
    acOutputFrequency = String()
    acOutputApparentCurrent = String()
    acOutputActivePower = String()
    outputLoadPercent = String()
    busVoltage = String()
    batteryVoltage = String()
    batteryChargingCurrent = String()
    batteryCapacitypercent = String()
    inverterHeatSinkTemperature = String()
    pvInputCurrentForBattery = String()
    pvInputVoltage = String()
    batteryVoltageFromScc = String()
    batteryDischargeCurrent = String()
    deviceStatus = String()
